"""Compare built-in layout modes without changing installed OCR or downloading."""
import json,re,time,statistics,hashlib
from pathlib import Path
from PIL import Image,ImageDraw,ImageFont,ImageOps
import tesserocr
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'build/ocr-columns';OUT.mkdir(exist_ok=True)
TEXT={
'en':(['Morning sunlight filled the room.','Sarah opened the first letter.','Travel plans were finally ready.','Everyone would leave on Friday.','Breakfast was served at eight.','The first journey ended in Oslo.'],['Afternoon rain arrived suddenly.','Michael waited beside the station.','Tickets cost exactly 125 kroner.','Nobody had forgotten the luggage.','Evening brought a clear blue sky.','The second journey ended in Bergen.']),
'nb':(['Morgensola fylte det store rommet.','Åse åpnet brevet fra biblioteket.','Reiseplanene var endelig klare.','Familien skulle dra på fredag.','Frokosten ble servert klokken åtte.','Den første reisen endte i Oslo.'],['Ettermiddagen kom med kraftig regn.','Øyvind ventet utenfor stasjonen.','Billettene kostet akkurat 125 kroner.','Bagasjen var pakket og klar.','Kvelden kom med en klar himmel.','Den andre reisen endte i Bergen.']),
'nn':(['Morgonsola fylte det store rommet.','Åse opna brevet frå biblioteket.','Reiseplanane var endeleg klare.','Familien skulle dra på fredag.','Frukosten vart servert klokka åtte.','Den første reisa enda i Oslo.'],['Ettermiddagen kom med kraftig regn.','Øyvind venta utanfor stasjonen.','Billettane kosta akkurat 125 kroner.','Bagasjen var pakka og klar.','Kvelden kom med ein klar himmel.','Den andre reisa enda i Bergen.'])}
def norm(text):return ' '.join(text.split())
def words(text):return re.findall(r"[^\W_]+",text.lower())
def edit(a,b):
 row=list(range(len(b)+1))
 for i,x in enumerate(a,1):
  nxt=[i]
  for j,y in enumerate(b,1):nxt.append(min(nxt[-1]+1,row[j]+1,row[j-1]+(x!=y)))
  row=nxt
 return row[-1]
fixtures=[]
for language,(left,right) in TEXT.items():
 for family in ('arial.ttf','times.ttf'):
  font=ImageFont.truetype('C:/Windows/Fonts/'+family,28)
  width=int(max(font.getlength(line) for line in left+right))+12
  for layout in ('plain','heading','narrow','staggered','footer'):
   gutter=24 if layout=='narrow' else 80
   heading='Two journeys: a report from Oslo and Bergen' if layout=='heading' else ''
   offset=56 if heading else 0;right_offset=23 if layout=='staggered' else 0
   image=Image.new('RGB',(64+width*2+gutter,370+offset),'white');draw=ImageDraw.Draw(image)
   if heading:
    titlefont=ImageFont.truetype('C:/Windows/Fonts/arialbd.ttf',34)
    assert width < titlefont.getlength(heading) < image.width-64
    draw.text((32,18),heading,font=titlefont,fill='black')
   for lines,x,y in ((left,32,32+offset),(right,32+width+gutter,32+offset+right_offset)):
    for index,line in enumerate(lines):draw.text((x,y+index*40),line,font=font,fill='black')
   footer='Document reference 804219' if layout=='footer' else ''
   if footer:draw.text((32,320+offset),footer,font=font,fill='black')
   expected=norm(' '.join([heading]+left+right+[footer]))
   anchors=[line.split()[0].lower() for line in left[:5]+right[:5]]
   name=f'{language}-{family}-{layout}';image.save(OUT/(name+'.png'))
   fixtures.append(dict(id=name,group='columns',image=image,expected=expected,anchors=anchors))
# Existing simple-crop regression controls, regenerated by ocr_screening.py if absent.
for sample in json.loads((ROOT/'docs/OCR_SCREENING.json').read_text(encoding='utf-8'))['results']:
 fixtures.append(dict(id=sample['id'],group='single',image=Image.open(ROOT/'build/ocr-screening'/(sample['id']+'.png')).convert('RGB'),expected=sample['expected'],anchors=[]))
rows=[]
for mode in (3,4,6,11):
 with tesserocr.PyTessBaseAPI(path=str(ROOT/'build/ocr-assets'),lang='nor+eng',psm=mode) as api:
  for fixture in fixtures:
   timings=[]
   for repeat in range(2):
    api.ClearAdaptiveClassifier();start=time.perf_counter();api.SetImage(ImageOps.expand(fixture['image'],border=16,fill='white'));actual=norm(api.GetUTF8Text());timings.append(time.perf_counter()-start)
   tokens=words(actual);positions=[tokens.index(a) if a in tokens else -1 for a in fixture['anchors']]
   ordered=all(p>=0 for p in positions) and positions==sorted(positions)
   rows.append(dict(id=fixture['id'],group=fixture['group'],psm=mode,expected=fixture['expected'],actual=actual,exact=actual==fixture['expected'],ordered=ordered if positions else None,anchor_positions=positions,character_errors=edit(fixture['expected'],actual),seconds=timings))
summary=[]
for mode in (3,4,6,11):
 for group in ('columns','single'):
  batch=[r for r in rows if r['psm']==mode and r['group']==group]
  entry=dict(psm=mode,group=group,count=len(batch),exact=sum(r['exact'] for r in batch),ordered=sum(r['ordered'] is True for r in batch) if group=='columns' else None,median_seconds=statistics.median(t for r in batch for t in r['seconds']))
  summary.append(entry);print(entry,flush=True)
(ROOT/'docs/OCR_COLUMNS.json').write_text(json.dumps(dict(engine=tesserocr.tesseract_version(),language='nor+eng',summary=summary,results=rows),ensure_ascii=False,indent=2),encoding='utf-8')
